name: aproxima
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^1.1.5
  drawing_animation: 0.0.4
  #flutter_sequence_animation: ^3.0.1
  firebase_dynamic_links:
  firebase_storage: 2.0.0
  #cloud_firestore: 0.3.0
  firebase_analytics: 2.0.0
  firebase_database: 2.0.0
  firebase_messaging: 3.0.0
  firebase_auth: ^0.8.0+3
  image_picker: 0.5.0+1
  firebase_core: ^0.3.0
  #app_review:
  flutter_search_panel: ^1.0.1

  location: 2.0.0
  shared_preferences: 0.4.0
  flutter_spinkit: "^3.1.0"
  json_annotation:
  camera:
  google_sign_in: 4.0.0
  share: 0.6.0
  photo_view:
  cached_network_image: ^0.5.1
  #flutter_facebook_login: "^1.1.1"
  #geolocator: 2.1.1
  #geoflutterfire: ^1.0.2
  geocoder: ^0.1.2
  flutter_swiper: ^1.1.4
  material_design_icons_flutter: 3.0.3392
  latlong:
  flutter_calendar_carousel:


  flutter_google_places_autocomplete: ^0.1.3

  flutter_slidable: 0.4.9

  video_player: 0.10.0


  #photo_view: ^0.0.10
  #zefyr: ^0.1.0
  unicorndial: "^1.1.5"
  timeago: ^2.0.10
  flutter_masked_text: ^0.7.0
  flutter_offline: "^0.2.1"
  flutter_typeahead: 0.6.1
  flutter_local_notifications: 0.5.0
  flip_panel: ^0.0.5
  flutter_search_bar: ^2.0.7
  launch_review: ^1.0.1
  #fluttertoast: ^2.0.8
  quick_actions: ^0.2.1
  #advanced_share: ^0.1.0
  #multi_image_picker: 3.0.11
  flutter_duration_picker: ^1.0.3
  date_range_picker: ^1.0.5
  #flutter_app_badger: ^1.0.2
  super_tooltip: ^0.9.0
  true_time: ^0.1.0
  #map_view: ^0.0.14
  #advanced_share: ^0.1.0
  #flutter_launch: ^0.1.2
  font_awesome_flutter: 8.2.0
  uuid: 1.0.3
  shimmer: ^1.0.0
  #share: ^0.5.3
  url_launcher: 5.0.0
  flutter_circular_chart: ^0.1.0
  #android_job_scheduler: ^0.0.7
  sqflite: any
  flutter_map: 0.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  google_maps_flutter: 0.4.0
  bloc_pattern: ^1.0.0
  rxdart:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  source_gen:
  built_value_generator:
  json_serializable:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/logo_sem_texto_teste.png
  - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages